---
name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Lint
        run: uv run --frozen pre-commit run --all-files

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Run type checks
        run: uv run --frozen pyright src tests


  test:
    name: Unit Tests - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests for given python version
        run: uv run --frozen pytest --cov=src/ezpit --cov-report=xml --cov-report=term

      # Uncomment once codecov is enabled.
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v5
      #   if: ${{ matrix.python-version == '3.13' }}  # Only upload coverage for Python 3.13 to avoid duplicates
      #   with:
      #     name: Coverage
      #     files: coverage.xml
      #     fail_ci_if_error: true
      #     token: ${{ secrets.CODECOV_TOKEN }}